name: Byzer Doc PR Check


on: 
  pull_request:
    branches:
      - main
jobs:
  checking:
    name: Byzer Doc CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]


    steps: 
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Env
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm install -g markdown-link-check

    - name: Run Checking Script
      run: ./.github/scripts/ci_checking.sh
      shell: bash
